# Generated by Django 5.0.1 on 2024-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='browserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostUrl', models.CharField(max_length=200)),
                ('pageUrl', models.CharField(max_length=200)),
                ('startTime', models.DateTimeField(verbose_name='start timestamp')),
                ('endTime', models.DateTimeField(verbose_name='end timestamp')),
                ('activeTime', models.IntegerField(default=0)),
                ('webType', models.CharField(max_length=200)),
            ],
        ),
    ]
