# Generated by Django 5.0.1 on 2024-01-28 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookAtData', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='browserHistory',
            new_name='UserActions',
        ),
    ]
