# Generated by Django 5.0.1 on 2024-01-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lookAtData', '0003_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
